### ISSUE TITLE
Allow entering serial device path

### ISSUE THREAD

**Issue by oliverlee** [oliverlee/phobos#176]
Not sure if there should be a splash screen? What about if the microcontroller is reset and the device name changes? Ideally we wouldn't need to restart the visual environment and could just change the device name to read from.

**Comment by mickvangelderen** [comment]
Ties into https://github.com/oliverlee/phobos/issues/177

**Comment by mickvangelderen** [comment]
This thing works.
![image](https://cloud.githubusercontent.com/assets/5444990/26117714/b22560c4-3a67-11e7-96af-186f7737b7ed.png)
It is horrible from a user standpoint however.

- no feedback
- no suggestions/autocomplete
- no navigation with the TAB key
- no autofocus
- no recent ports

It does have a [platform specific default port](https://gitlab.com/bikelab/phobos-visualizer/blob/b56d249211a3188e9ed0c9cab92b6b611b101f71/Assets/Scripts/Configuration.cs#L16-24)

**Comment by mickvangelderen** [comment]
Not restarting the visualizer will be a challenge https://github.com/oliverlee/phobos/issues/185

**Comment by mickvangelderen** [comment]
Design for the screen:

```
Serial Device Port: 
⊙ Detected: [ /dev/ttyACM0 | V ]
○ Manual:   _________________

[ Connect ]
```

We will look for files matching a regex (for example `\/dev\/ttyACM\d+`), specific to the platform we are running on. On windows we could perhaps use `SerialPort.GetPortNames()` because the serial devices are probably not files on the filesystem.

The detection should run periodically while the screen is active.

When 1) no data is coming from the serial port for more than 100ms, 2) we cannot succesfully interpret the incoming data, or 3) the user presses the disconnect button, we should close the connection and all associated resources and reopen the port selection screen.

**Comment by mickvangelderen** [comment]
Took a while but after some frustration, forum hunting and tutorial watching I figured out how auto layout (somtimes) works in Unity. Feel failrly confident I can add other configuration options, buttons and what not in the future with relative ease.

![image](https://cloud.githubusercontent.com/assets/5444990/26208294/0298ca54-3bea-11e7-8076-c47a911d8343.png)

**Comment by mickvangelderen** [comment]
Works really well right now. 
![image](https://user-images.githubusercontent.com/5444990/27377520-7cbb7ea8-5675-11e7-8b9b-c4bd49be3cb5.png)
