### ISSUE TITLE
Unable to build phoviz on windows

### ISSUE THREAD

**Issue by oliverlee** [oliverlee/phobos#228]
Build fails due to compiler error:
```
The type or namespace name 'Concurrent' does not exist in the namespace 'System.Collections'. Are you missing an assembly reference?
```

**Comment by mickvangelderen** [comment]
I implemented a concurrent bounded queue and am using it reliably in the `Live` scene. The `Replay` scene is still using some old code. This can be fixed relatively easily. 

The reason I haven't updated the `Replay` scene is because the COBS and Protobuf decoding for a pull based stream with timeouts of which we cannot use the underlying `Stream` class (serial port) and a pull based stream (file stream) is not easily abstracted.

**Comment by mickvangelderen** [comment]
Moved issue to Improved Demo because the replay functionality is not essential.

**Comment by mickvangelderen** [comment]
https://gitlab.com/bikelab/phobos-visualizer/commit/2d85b200915c19c2b20607c71157d45140151fc9
